export enum PostActionTypes {
  LIKE_POST = 'LIKE_POST',
  UNLIKE_POST = 'UNLIKE_POST',
  ADD_TEACHER_RATING = 'ADD_TEACHER_RATING',
  ADD_SUBJECT_RATING = 'ADD_SUBJECT_RATING',
  UPDATE_TEACHER_RATING = 'UPDATE_TEACHER_RATING',
  UPDATE_SUBJECT_RATING = 'UPDATE_SUBJECT_RATING',
  LOAD_POSTS = 'LOAD_POSTS',
  ADD_POST = 'ADD_POST'
} 